#!/usr/bin/env python3
"""Render the browsable half of the Helm repository.

The gh-pages branch carries index.yaml, which every `helm repo add` consumes and
no human reads -- the branch has no index.html at all, so the repository URL in a
browser is a 404. This writes the other half beside it: a landing page listing
the published charts, and one page per chart carrying its generated README, the
versions actually published, and the upstream image it tracks.

Everything is derived. index.yaml is the truth about what is published; the chart
directory on main is the truth about what the current version documents. Nothing
on the branch is written by hand, so nothing on it can go stale on its own -- the
one failure mode a hand-kept version table would have.

The generator writes only what it owns (index.html, the per-chart directories,
assets/ and the branch README). index.yaml belongs to chart-releaser and is read,
never touched.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import shutil
import sys
from pathlib import Path

import markdown
import yaml

ANNOTATION_PREFIX = "charts.rgielen.de/"

# Labels for the upstream-tracking annotations. An annotation without an entry
# here is still shown, under its own name -- adding one to a chart should not
# need a change here to become visible.
ANNOTATION_LABELS = {
    "upstream-image": "Tracked image",
    "upstream-tag-pattern": "Tag pattern",
    "upstream-releases": "Release notes",
    "upstream-watch-paths": "Watched files",
    "upstream-config-sources": "Config sources",
}

# The tail helm-docs appends to every chart README. True on GitHub, meaningless
# on a rendered page, and the page carries its own note about being generated.
HELM_DOCS_FOOTER = re.compile(r"\n-{3,}\s*\n+_This file is generated by \[helm-docs\].*\Z", re.S)

SEMVER = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:[-+](.*))?$")


def version_key(version: str) -> tuple:
    """Sort key, newest first when reversed.

    A release without a parseable version sorts below every parseable one rather
    than raising: the index is allowed to contain history this script did not
    write.
    """
    match = SEMVER.match(str(version).strip())
    if not match:
        return (0, 0, 0, 0, str(version))
    major, minor, patch, pre = match.groups()
    # A prerelease precedes its own release, and sorts after the previous patch.
    return (int(major), int(minor), int(patch), 0 if pre else 1, pre or "")


def load_index(path: Path) -> dict[str, list[dict]]:
    """Read index.yaml into {chart name: [entry, ...]}, newest version first."""
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text()) or {}
    entries = data.get("entries") or {}
    return {
        name: sorted(versions, key=lambda e: version_key(e.get("version", "")), reverse=True)
        for name, versions in entries.items()
    }


def index_generated(path: Path) -> str:
    if not path.is_file():
        return ""
    data = yaml.safe_load(path.read_text()) or {}
    return str(data.get("generated", ""))[:10]


def released_on(entry: dict) -> str:
    """The date part of `created`.

    Sliced rather than parsed: helm writes nine fractional digits, which
    datetime.fromisoformat rejects, and an unquoted value would already have come
    out of the YAML load as a datetime. A date is all the page shows anyway.
    """
    return str(entry.get("created", ""))[:10]


def strip_readme_header(text: str) -> str:
    """Drop the README's own title and badge line.

    The page draws both itself, from Chart.yaml, and the badges are remote
    images. Dropping the h1 also leaves the document starting at h2, which is the
    right level below the page heading.
    """
    lines = text.splitlines()
    cursor = 0
    if cursor < len(lines) and lines[cursor].startswith("# "):
        cursor += 1
        while cursor < len(lines) and not lines[cursor].strip():
            cursor += 1
        if cursor < len(lines) and "img.shields.io" in lines[cursor]:
            cursor += 1
    return "\n".join(lines[cursor:]).lstrip("\n")


def cell(value: str) -> str:
    """Escape a value for a Markdown table cell."""
    return str(value).replace("|", "\\|")


def versions_section(name: str, entries: list[dict], repository: str) -> str:
    """The version history, as Markdown so it lands in the page's table of contents."""
    if not entries:
        return ""
    rows = [
        "## Published versions",
        "",
        "Every version below is installable and immutable — a published version is never",
        "re-released with different content.",
        "",
        "| Version | App version | Released | Package | Digest |",
        "| ------- | ----------- | -------- | ------- | ------ |",
    ]
    for entry in entries:
        version = str(entry.get("version", ""))
        urls = entry.get("urls") or []
        package = f"[`.tgz`]({urls[0]})" if urls else "—"
        release = f"https://github.com/{repository}/releases/tag/{name}-{version}"
        digest = str(entry.get("digest", ""))
        rows.append(
            "| [`{version}`]({release}) | `{app}` | {date} | {package} | `{digest}` |".format(
                version=cell(version),
                release=release,
                app=cell(entry.get("appVersion", "—")),
                date=released_on(entry) or "—",
                package=package,
                digest=cell(digest[:19] + "…") if digest else "—",
            )
        )
    return "\n".join(rows) + "\n"


def upstream_section(annotations: dict, app_version: str) -> str:
    """What the nightly image watch is pointed at, for the charts that opt in."""
    tracked = {
        key[len(ANNOTATION_PREFIX):]: value
        for key, value in (annotations or {}).items()
        if key.startswith(ANNOTATION_PREFIX)
    }
    if not tracked:
        return ""
    rows = [
        "## Upstream tracking",
        "",
        "This chart's `appVersion` follows a container image. A scheduled workflow watches",
        "that image, diffs the watched files between the two image commits, and opens a",
        "pull request that bumps `appVersion` and the chart `version` together. It merges",
        "unattended only when the bump is not a major one and the diff is clean.",
        "",
        "| Setting | Value |",
        "| ------- | ----- |",
    ]
    # Known annotations in the order they are declared above, which reads better
    # than alphabetical; anything added later follows, sorted.
    order = list(ANNOTATION_LABELS)
    for key in sorted(tracked, key=lambda k: (order.index(k) if k in order else len(order), k)):
        label = ANNOTATION_LABELS.get(key, key.replace("-", " ").capitalize())
        value = str(tracked[key])
        if key == "upstream-releases":
            # The template carries a {version} placeholder. Filled in with the
            # version this chart currently packages, it is the one link a reader
            # actually wants -- with the caveat that the upstream does not cut a
            # release for every image tag it publishes.
            url = value.replace("{version}", app_version)
            rendered = f"[{cell(url.rsplit('/', 1)[-1])}]({url}) — not every image tag has one"
        elif "," in value:
            rendered = ", ".join(f"`{cell(part)}`" for part in value.split(","))
        else:
            rendered = f"`{cell(value)}`"
        rows.append(f"| {label} | {rendered} |")
    return "\n".join(rows) + "\n"


def toc_html(tokens: list[dict]) -> str:
    """A two-level table of contents from python-markdown's parsed headings."""
    items = []
    for token in tokens:
        items.append(
            '<li><a href="#{id}">{name}</a>'.format(id=token["id"], name=html.escape(token["name"]))
        )
        children = token.get("children") or []
        if children:
            items.append("<ul>")
            items.extend(
                '<li><a href="#{id}">{name}</a></li>'.format(
                    id=child["id"], name=html.escape(child["name"])
                )
                for child in children
            )
            items.append("</ul>")
        items.append("</li>")
    if not items:
        return ""
    return '<nav class="toc" aria-label="On this page"><p class="toc-title">On this page</p><ul>{items}</ul></nav>'.format(
        items="".join(items)
    )


def render_markdown(text: str) -> tuple[str, str]:
    """Convert a document, returning its HTML body and a table of contents."""
    converter = markdown.Markdown(
        extensions=["extra", "sane_lists", "toc"],
        extension_configs={"toc": {"permalink": "#", "permalink_class": "anchor", "toc_depth": "2-3"}},
    )
    body = converter.convert(text)
    # Values tables are wider than any phone. Wrapping them keeps the scroll
    # inside the table instead of on the page body.
    body = body.replace("<table>", '<div class="table-wrap"><table>').replace("</table>", "</table></div>")
    return body, toc_html(converter.toc_tokens)


def document(*, title: str, description: str, body: str, root: str, repository: str) -> str:
    return """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="color-scheme" content="light dark">
<link rel="stylesheet" href="{root}assets/style.css">
</head>
<body>
<header class="site-header">
<a class="brand" href="{root}">rgielen Helm Charts</a>
<nav class="site-nav">
<a href="{root}index.yaml">index.yaml</a>
<a href="https://github.com/{repository}">GitHub</a>
</nav>
</header>
{body}
<footer class="site-footer">
<p>Generated from <a href="{root}index.yaml"><code>index.yaml</code></a> and the chart sources
by <a href="https://github.com/{repository}/blob/main/.github/scripts/build_pages.py"><code>build_pages.py</code></a>.
This branch is machine-managed; edit the chart, not the page.</p>
</footer>
</body>
</html>
""".format(
        title=html.escape(title),
        description=html.escape(description),
        body=body,
        root=root,
        repository=repository,
    )


def badges(chart: dict) -> str:
    parts = [
        f'<span class="badge"><span>Chart</span><b>{html.escape(str(chart.get("version", "")))}</b></span>'
    ]
    if chart.get("appVersion"):
        parts.append(
            f'<span class="badge"><span>App</span><b>{html.escape(str(chart["appVersion"]))}</b></span>'
        )
    parts.append(
        f'<span class="badge"><span>Type</span><b>{html.escape(str(chart.get("type", "application")))}</b></span>'
    )
    return '<p class="badges">' + "".join(parts) + "</p>"


def chart_page(*, chart: dict, readme: str, entries: list[dict], repository: str) -> str:
    name = str(chart.get("name", ""))
    version = str(chart.get("version", ""))
    published = [str(entry.get("version", "")) for entry in entries]
    latest = published[0] if published else ""

    # The README already carries an Installation section with both commands and
    # its own version, so the page adds none of its own. That version is the one
    # in Chart.yaml, which the banner below qualifies when it is not published.
    document_md = strip_readme_header(HELM_DOCS_FOOTER.sub("", readme))
    for section in (
        versions_section(name, entries, repository),
        upstream_section(chart.get("annotations") or {}, str(chart.get("appVersion", ""))),
    ):
        if section:
            document_md += "\n\n" + section
    body, toc = render_markdown(document_md)

    notices = []
    if not published:
        notices.append(
            "<div class=\"notice\"><b>Not published yet.</b> This chart exists on <code>main</code> "
            "but no version of it is in the repository index.</div>"
        )
    elif version not in published:
        # The one failure this repository is built around: the release workflow
        # publishes only versions that do not exist yet, so a chart edited
        # without a version bump produces a green run that ships nothing.
        notices.append(
            "<div class=\"notice warn\"><b>Version <code>{version}</code> is not published.</b> "
            "The documentation below describes it, the newest published version is "
            "<code>{latest}</code>. Either the release is still running, or a change was merged "
            "without a chart <code>version</code> bump — which the release workflow skips "
            "silently.</div>".format(version=html.escape(version), latest=html.escape(latest))
        )

    main = """<main class="chart">
<p class="crumbs"><a href="../">Charts</a> <span>/</span> {name}</p>
<h1>{name}</h1>
<p class="lede">{description}</p>
{badges}
{notices}
<div class="layout">
{toc}
<article class="prose">
{body}
</article>
</div>
</main>""".format(
        name=html.escape(name),
        description=html.escape(str(chart.get("description", ""))),
        badges=badges(chart),
        notices="".join(notices),
        toc=toc,
        body=body,
    )

    return document(
        title=f"{name} — rgielen Helm Charts",
        description=str(chart.get("description", "")),
        body=main,
        root="../",
        repository=repository,
    )


def chart_card(name: str, chart: dict, entries: list[dict], repository: str) -> str:
    latest = str(entries[0].get("version", "")) if entries else ""
    app = str(entries[0].get("appVersion", "")) if entries else str(chart.get("appVersion", ""))
    keywords = "".join(
        f'<span class="chip">{html.escape(str(word))}</span>' for word in (chart.get("keywords") or [])[:6]
    )
    icon = chart.get("icon")
    icon_html = (
        f'<img class="icon" src="{html.escape(str(icon))}" alt="" loading="lazy" width="32" height="32">'
        if icon
        else ""
    )
    links = []
    if chart.get("home"):
        links.append(f'<a href="{html.escape(str(chart["home"]))}">Project</a>')
    # Every chart lists this repository among its sources; the interesting one is
    # the other entry, the project the chart packages.
    for source in chart.get("sources") or []:
        if repository not in str(source):
            links.append(f'<a href="{html.escape(str(source))}">Upstream</a>')
            break
    return """<li class="card">
<a class="card-head" href="{name}/">{icon}<span class="card-title">{name}</span></a>
<p class="card-desc">{description}</p>
<p class="badges">{version}{appversion}</p>
<p class="chips">{keywords}</p>
<p class="card-links"><a href="{name}/">Documentation</a>{links}</p>
</li>""".format(
        name=html.escape(name),
        icon=icon_html,
        description=html.escape(str(chart.get("description", ""))),
        version=(
            f'<span class="badge"><span>Chart</span><b>{html.escape(latest)}</b></span>'
            if latest
            else '<span class="badge warn"><b>unreleased</b></span>'
        ),
        appversion=f'<span class="badge"><span>App</span><b>{html.escape(app)}</b></span>' if app else "",
        keywords=keywords,
        links="".join(f' <span>·</span> {link}' for link in links),
    )


def landing_page(
    *,
    charts: list[tuple[str, dict, list[dict]]],
    repository: str,
    pages_url: str,
    oci_url: str,
    generated: str,
) -> str:
    cards = "".join(chart_card(name, chart, entries, repository) for name, chart, entries in charts)
    updated = f'<p class="muted">Index last updated {html.escape(generated)}.</p>' if generated else ""

    main = """<main class="landing">
<h1>rgielen Helm Charts</h1>
<p class="lede">Helm charts maintained by <a href="https://github.com/{owner}">@{owner}</a>, released
independently from <a href="https://github.com/{repository}">one repository</a>. Written for GitOps
consumption, and equally happy under a plain <code>helm install</code>.</p>

<div class="install">
<h2>Add the repository</h2>
<pre><code>helm repo add rgielen {pages}
helm repo update
helm search repo rgielen</code></pre>
<p>Every release is published twice, with identical content: here, and as an OCI artifact at
<code>oci://{oci}/&lt;chart&gt;</code>. Pin an explicit version — for an ArgoCD
<code>targetRevision</code> a floating range turns an unrelated upstream release into an
unreviewed change in your cluster.</p>
</div>

<h2 id="charts">Charts</h2>
<ul class="cards">
{cards}
</ul>
{updated}
</main>""".format(
        owner=html.escape(repository.split("/")[0]),
        repository=html.escape(repository),
        pages=html.escape(pages_url),
        oci=html.escape(oci_url),
        cards=cards,
        updated=updated,
    )

    return document(
        title="rgielen Helm Charts",
        description="Helm charts released independently from a single repository, published to GitHub Pages and ghcr.io.",
        body=main,
        root="./",
        repository=repository,
    )


BRANCH_README = """# rgielen Helm chart repository

This branch is machine-managed. It carries the repository index that
[`helm/chart-releaser-action`](https://github.com/helm/chart-releaser-action) writes, and the
browsable pages that
[`.github/scripts/build_pages.py`](https://github.com/{repository}/blob/main/.github/scripts/build_pages.py)
renders from that index and the chart sources. Do not commit to it by hand — the next release
overwrites everything but `index.yaml`.

```bash
helm repo add rgielen {pages}
helm repo update
helm search repo rgielen
```

Rendered: <{pages}/>. Sources, documentation and issues live on
[`main`](https://github.com/{repository}).
"""


def build(
    *,
    charts_dir: Path,
    index_path: Path,
    output: Path,
    assets: Path,
    repository: str,
    pages_url: str,
    oci_url: str,
) -> list[str]:
    published = load_index(index_path)
    written: list[str] = []

    # The chart's own `name` is what index.yaml and `helm install` use; the
    # directory only has to match by convention, so both are carried along.
    discovered: list[tuple[str, dict, list[dict], Path]] = []
    for chart_yaml in sorted(charts_dir.glob("*/Chart.yaml")):
        chart = yaml.safe_load(chart_yaml.read_text()) or {}
        name = str(chart.get("name") or chart_yaml.parent.name)
        discovered.append((name, chart, published.get(name, []), chart_yaml.parent))

    if not discovered:
        print("No chart found under charts/ -- nothing to render.", file=sys.stderr)

    for name, chart, entries, directory in discovered:
        readme_path = directory / "README.md"
        readme = readme_path.read_text() if readme_path.is_file() else ""
        if not readme:
            print(f"::warning::{name} has no generated README.md; its page will be thin.", file=sys.stderr)
        page = chart_page(chart=chart, readme=readme, entries=entries, repository=repository)
        target = output / name / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page)
        written.append(str(target.relative_to(output)))

    (output / "index.html").write_text(
        landing_page(
            charts=[(name, chart, entries) for name, chart, entries, _ in discovered],
            repository=repository,
            pages_url=pages_url,
            oci_url=oci_url,
            generated=index_generated(index_path),
        )
    )
    written.append("index.html")

    (output / "assets").mkdir(parents=True, exist_ok=True)
    shutil.copy2(assets / "style.css", output / "assets" / "style.css")
    written.append("assets/style.css")

    (output / "README.md").write_text(BRANCH_README.format(repository=repository, pages=pages_url))
    written.append("README.md")

    # Pages runs Jekyll over a branch without it, which would drop anything whose
    # name begins with an underscore and slow every deploy down for nothing.
    nojekyll = output / ".nojekyll"
    if not nojekyll.exists():
        nojekyll.write_text("")
        written.append(".nojekyll")

    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--charts", type=Path, default=Path("charts"), help="Chart directory tree.")
    parser.add_argument(
        "--index",
        type=Path,
        required=True,
        help="index.yaml from the published branch. Read, never written.",
    )
    parser.add_argument("--output", type=Path, required=True, help="Directory to render into.")
    parser.add_argument("--assets", type=Path, default=Path(".github/site"), help="Static assets to copy.")
    parser.add_argument(
        "--repository",
        default=os.environ.get("GITHUB_REPOSITORY", "rgielen/charts"),
        help="owner/name, used for every generated link.",
    )
    args = parser.parse_args()

    owner, _, repo = args.repository.partition("/")
    written = build(
        charts_dir=args.charts,
        index_path=args.index,
        output=args.output,
        assets=args.assets,
        repository=args.repository,
        pages_url=f"https://{owner}.github.io/{repo}",
        oci_url=f"ghcr.io/{owner}/charts",
    )
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
