{{/*
Expand the name of the chart.
*/}}
{{- define "manifest-llm-gateway.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Fully qualified app name.
*/}}
{{- define "manifest-llm-gateway.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "manifest-llm-gateway.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "manifest-llm-gateway.labels" -}}
helm.sh/chart: {{ include "manifest-llm-gateway.chart" . }}
{{ include "manifest-llm-gateway.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "manifest-llm-gateway.selectorLabels" -}}
app.kubernetes.io/name: {{ include "manifest-llm-gateway.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "manifest-llm-gateway.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "manifest-llm-gateway.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Service account for the migration hook.

The chart's own ServiceAccount is a release resource, and a pre-install hook runs
before any of those exist -- naming it there makes the Job controller retry
"serviceaccount not found" until the hook times out. So the hook uses it only
when it is *not* chart-managed, and therefore already present. An explicitly
configured name always wins: a pre-existing account is the way to give the
migration pod a cloud workload identity for a managed database.
*/}}
{{- define "manifest-llm-gateway.migrationServiceAccountName" -}}
{{- if .Values.manifest.migrations.job.serviceAccountName }}
{{- .Values.manifest.migrations.job.serviceAccountName }}
{{- else if not .Values.serviceAccount.create }}
{{- include "manifest-llm-gateway.serviceAccountName" . }}
{{- else }}
{{- "default" }}
{{- end }}
{{- end }}

{{- define "manifest-llm-gateway.image" -}}
{{- printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
{{- end }}

{{/*
Name of the claim holding locally stored request recordings.
*/}}
{{- define "manifest-llm-gateway.recordingsClaimName" -}}
{{- default (printf "%s-recordings" (include "manifest-llm-gateway.fullname" .)) .Values.persistence.existingClaim }}
{{- end }}

{{/*
The URL the dashboard is reached at. Falls back to the first Ingress host so the
common case needs no second place to keep the hostname in sync.
*/}}
{{- define "manifest-llm-gateway.publicUrl" -}}
{{- if .Values.manifest.publicUrl }}
{{- .Values.manifest.publicUrl }}
{{- else if and .Values.ingress.enabled .Values.ingress.hosts }}
{{- $host := (first .Values.ingress.hosts).host }}
{{- $scheme := "http" }}
{{- range .Values.ingress.tls }}
{{- if has $host .hosts }}{{ $scheme = "https" }}{{ end }}
{{- end }}
{{- printf "%s://%s" $scheme $host }}
{{- end }}
{{- end }}

{{/*
Rollout strategy.

Defaults to Recreate whenever the pods share a volume that cannot be mounted
twice: a RollingUpdate would wait forever for the new pod to attach a
ReadWriteOnce claim the old one still holds. Without such a claim there is
nothing to serialize on, so a surge-first rolling update is both safe and the
better default -- it is what keeps a multi-replica install available across an
upgrade.
*/}}
{{- define "manifest-llm-gateway.updateStrategy" -}}
{{- if .Values.updateStrategy }}
{{- toYaml .Values.updateStrategy }}
{{- else if and .Values.persistence.enabled (not (has "ReadWriteMany" .Values.persistence.accessModes)) }}
type: Recreate
{{- else }}
type: RollingUpdate
rollingUpdate:
  maxUnavailable: 0
  maxSurge: 1
{{- end }}
{{- end }}

{{/*
Refuse to render without the two settings that have no safe default.

Neither is ever generated by the chart. This chart is rendered by ArgoCD, which
runs `helm template` without cluster access, so `lookup` returns nothing: a
generated secret would differ on every sync, invalidating all sessions and --
worse -- making every stored provider credential undecryptable.
*/}}
{{- define "manifest-llm-gateway.validate" -}}
{{- if not (or .Values.manifest.auth.secret .Values.manifest.existingSecret) }}
{{- fail "manifest-llm-gateway: no session signing secret. Set manifest.auth.secret (generate with `openssl rand -hex 32`), or set manifest.existingSecret to a Secret that contains a BETTER_AUTH_SECRET key. The chart deliberately never generates one." }}
{{- end }}
{{- if not (or .Values.manifest.database.url .Values.manifest.existingSecret) }}
{{- fail "manifest-llm-gateway: no database. Set manifest.database.url, or set manifest.existingSecret to a Secret that contains a DATABASE_URL key. This chart does not deploy PostgreSQL -- see the chart README." }}
{{- end }}
{{- if not (or .Values.manifest.migrations.job.enabled .Values.manifest.runMigrationsOnBoot) }}
{{- fail "manifest-llm-gateway: nothing would apply database migrations. Enable manifest.migrations.job.enabled, or set manifest.runMigrationsOnBoot=true, or apply them yourself and knowingly set both to false only after removing this guard." }}
{{- end }}
{{- if and (gt (int .Values.replicaCount) 1) .Values.manifest.runMigrationsOnBoot }}
{{- fail "manifest-llm-gateway: replicaCount > 1 with manifest.runMigrationsOnBoot=true will hang the rollout, not just race. The boot path applies migrations without the advisory lock the upstream's migration entry point takes, and one of the pending migrations is a CREATE INDEX CONCURRENTLY -- which waits for the other replicas' sessions, while those wait for the lock. Nothing breaks the cycle. Use the migration Job (manifest.migrations.job.enabled=true, the default) and leave runMigrationsOnBoot=false." }}
{{- end }}
{{- if and (gt (int .Values.replicaCount) 1) .Values.persistence.enabled (not .Values.manifest.recordings.s3.bucket) (not (has "ReadWriteMany" .Values.persistence.accessModes)) }}
{{- fail "manifest-llm-gateway: replicaCount > 1 with a ReadWriteOnce recordings volume. The replicas cannot share it, so all but the first stay Pending. Configure manifest.recordings.s3 instead, or set persistence.accessModes to include ReadWriteMany if your storage supports it." }}
{{- end }}
{{- end }}

{{/*
Add key/value to a dict, skipping nil and empty values.

Empty is not the same as absent for this application: several settings are read
as `Number(env ?? default)`, where an empty string coerces to 0 instead of
falling back to the default. So an unset value must not reach the container at
all. Booleans are stringified first, which keeps a deliberate `false` in place.

Usage: {{- include "manifest-llm-gateway.put" (list $dict "KEY" $value) }}
*/}}
{{- define "manifest-llm-gateway.put" -}}
{{- $dict := index . 0 }}
{{- $key := index . 1 }}
{{- $value := index . 2 }}
{{- if not (kindIs "invalid" $value) }}
{{- $rendered := toString $value }}
{{- if ne $rendered "" }}
{{- $_ := set $dict $key $rendered }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Non-sensitive environment, as `key: "value"` lines for a ConfigMap.
*/}}
{{- define "manifest-llm-gateway.plainEnv" -}}
{{- $m := .Values.manifest }}
{{- $d := dict }}
{{- include "manifest-llm-gateway.put" (list $d "PORT" $m.port) }}
{{- include "manifest-llm-gateway.put" (list $d "BETTER_AUTH_URL" (include "manifest-llm-gateway.publicUrl" .)) }}
{{- include "manifest-llm-gateway.put" (list $d "MANIFEST_MODE" $m.mode) }}
{{- include "manifest-llm-gateway.put" (list $d "WINGMAN_CORS_ORIGINS" (join "," $m.corsOrigins)) }}
{{- if $m.disableHsts }}
{{- include "manifest-llm-gateway.put" (list $d "MANIFEST_DISABLE_HSTS" "1") }}
{{- end }}

{{- include "manifest-llm-gateway.put" (list $d "DB_POOL_MAX" $m.database.poolMax) }}
{{- include "manifest-llm-gateway.put" (list $d "AUTH_DB_POOL_MAX" $m.database.authPoolMax) }}
{{- include "manifest-llm-gateway.put" (list $d "DB_TUNE_SESSION" $m.database.tuneSession) }}
{{- include "manifest-llm-gateway.put" (list $d "RUN_MIGRATIONS_ON_BOOT" $m.runMigrationsOnBoot) }}

{{- include "manifest-llm-gateway.put" (list $d "PROVIDER_TIMEOUT_MS" $m.proxy.providerTimeoutMs) }}
{{- include "manifest-llm-gateway.put" (list $d "STREAM_WARMUP_MS" $m.proxy.streamWarmupMs) }}
{{- include "manifest-llm-gateway.put" (list $d "CODEX_SEMANTIC_OUTPUT_TIMEOUT_MS" $m.proxy.codexSemanticOutputTimeoutMs) }}
{{- include "manifest-llm-gateway.put" (list $d "MANIFEST_CONCURRENCY_MAX" $m.proxy.concurrencyMax) }}
{{- include "manifest-llm-gateway.put" (list $d "OLLAMA_HOST" $m.ollamaHost) }}

{{- include "manifest-llm-gateway.put" (list $d "CREDITS_BASE_URL" $m.credits.baseUrl) }}
{{- include "manifest-llm-gateway.put" (list $d "CREDITS_AUTO_PROVISION_ALLOWLIST" (join "," $m.credits.autoProvisionAllowlist)) }}
{{- include "manifest-llm-gateway.put" (list $d "CREDITS_GEMINI_FREE_MAX_BUDGET" $m.credits.geminiFreeMaxBudget) }}

{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_STORAGE" $m.recordings.storage) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_FILESYSTEM_PATH" $m.recordings.filesystemPath) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_RETENTION_DAYS" $m.recordings.retentionDays) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_BUCKET" $m.recordings.s3.bucket) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_ENDPOINT" $m.recordings.s3.endpoint) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_REGION" $m.recordings.s3.region) }}
{{- if $m.recordings.s3.bucket }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_FORCE_PATH_STYLE" $m.recordings.s3.forcePathStyle) }}
{{- end }}

{{- include "manifest-llm-gateway.put" (list $d "EMAIL_PROVIDER" $m.email.provider) }}
{{- include "manifest-llm-gateway.put" (list $d "EMAIL_DOMAIN" $m.email.domain) }}
{{- include "manifest-llm-gateway.put" (list $d "EMAIL_FROM" $m.email.from) }}

{{- include "manifest-llm-gateway.put" (list $d "GOOGLE_CLIENT_ID" $m.oauth.google.clientId) }}
{{- include "manifest-llm-gateway.put" (list $d "GITHUB_CLIENT_ID" $m.oauth.github.clientId) }}
{{- include "manifest-llm-gateway.put" (list $d "DISCORD_CLIENT_ID" $m.oauth.discord.clientId) }}
{{- include "manifest-llm-gateway.put" (list $d "OPENAI_OAUTH_CLIENT_ID" $m.providerOauth.openaiClientId) }}
{{- include "manifest-llm-gateway.put" (list $d "MINIMAX_OAUTH_CLIENT_ID" $m.providerOauth.minimaxClientId) }}

{{- include "manifest-llm-gateway.put" (list $d "THROTTLE_TTL" $m.throttle.ttl) }}
{{- include "manifest-llm-gateway.put" (list $d "THROTTLE_LIMIT" $m.throttle.limit) }}
{{- include "manifest-llm-gateway.put" (list $d "SHUTDOWN_DRAIN_MS" $m.shutdownDrainMs) }}

{{- include "manifest-llm-gateway.put" (list $d "SENTRY_ENVIRONMENT" $m.sentry.environment) }}
{{- include "manifest-llm-gateway.put" (list $d "SENTRY_RELEASE" $m.sentry.release) }}
{{- include "manifest-llm-gateway.put" (list $d "MANIFEST_TELEMETRY_DISABLED" (ternary "1" "0" $m.telemetry.disabled)) }}
{{- include "manifest-llm-gateway.put" (list $d "TELEMETRY_ENDPOINT" $m.telemetry.endpoint) }}

{{- /* Hardcoded for the same reason the upstream compose file hardcodes them:
       the image is a production artefact, and the seeder refuses to run under
       NODE_ENV=production anyway. Offering these as knobs would only offer a
       setting that cannot take effect. */ -}}
{{- $_ := set $d "SEED_DATA" "false" }}
{{- $_ := set $d "NODE_ENV" "production" }}

{{- toYaml $d }}
{{- end }}

{{/*
Sensitive environment, as `key: "value"` lines for a Secret's stringData.
*/}}
{{- define "manifest-llm-gateway.secretEnv" -}}
{{- $m := .Values.manifest }}
{{- $d := dict }}
{{- include "manifest-llm-gateway.put" (list $d "BETTER_AUTH_SECRET" $m.auth.secret) }}
{{- include "manifest-llm-gateway.put" (list $d "MANIFEST_ENCRYPTION_KEY" $m.auth.encryptionKey) }}
{{- include "manifest-llm-gateway.put" (list $d "DATABASE_URL" $m.database.url) }}
{{- include "manifest-llm-gateway.put" (list $d "MIGRATION_DATABASE_URL" $m.database.migrationUrl) }}
{{- include "manifest-llm-gateway.put" (list $d "API_KEY" $m.apiKey) }}
{{- include "manifest-llm-gateway.put" (list $d "EMAIL_API_KEY" $m.email.apiKey) }}
{{- include "manifest-llm-gateway.put" (list $d "GOOGLE_CLIENT_SECRET" $m.oauth.google.clientSecret) }}
{{- include "manifest-llm-gateway.put" (list $d "GITHUB_CLIENT_SECRET" $m.oauth.github.clientSecret) }}
{{- include "manifest-llm-gateway.put" (list $d "DISCORD_CLIENT_SECRET" $m.oauth.discord.clientSecret) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_ACCESS_KEY_ID" $m.recordings.s3.accessKeyId) }}
{{- include "manifest-llm-gateway.put" (list $d "REQUEST_RECORDING_S3_SECRET_ACCESS_KEY" $m.recordings.s3.secretAccessKey) }}
{{- include "manifest-llm-gateway.put" (list $d "CREDITS_MASTER_KEY" $m.credits.masterKey) }}
{{- include "manifest-llm-gateway.put" (list $d "SENTRY_DSN" $m.sentry.dsn) }}
{{- /* An empty dict renders as "{}", which is not empty -- callers test this
       output to decide whether to create a Secret at all. */ -}}
{{- if $d }}{{ toYaml $d }}{{ end }}
{{- end }}
