apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manifest-llm-gateway.fullname" . }}
  labels:
    {{- include "manifest-llm-gateway.labels" . | nindent 4 }}
data:
  {{- include "manifest-llm-gateway.plainEnv" . | nindent 2 }}
