{{- $data := include "manifest-llm-gateway.secretEnv" . }}
{{- if trim $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manifest-llm-gateway.fullname" . }}
  labels:
    {{- include "manifest-llm-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $data | nindent 2 }}
{{- end }}
